---
- name: Install required system package
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - git
    - curl
    - gnupg
    - wget
    - unzip
  tags: install

- name: Add  apt key
  apt_key:
    url: https://www.mongodb.org/static/pgp/server-4.2.asc
    state: present
  tags: install

- name: Add repository
  apt_repository:
    repo: deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.2 multiverse
    filename: mongodb-org-4.2
    state: present
  tags: install

- name: Install mongodb
  apt:
    name: mongodb-org
    state: present
    update_cache: yes
  tags: install

- name: enable mongo
  systemd:
    name: mongod
    state: started
    enabled: yes
  tags: install
