---
- name: Install required system package
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - git
    - ruby-full
    - ruby-bundler
    - build-essential
  tags: ruby
